### ISSUE TITLE
Problem with custom format

### ISSUE THREAD

**Issue by nesalkiN** [dattas/OctoPrint-DetailedProgress#20]
I have this in my config.yaml. I don't know if it is related.

>    detailedprogress:
>     eta_strftime: '%-d/%-m %H:%M:%S'
>     etl_format: '{hours:02d}t{minutes:02d}m{seconds:02d}s'
>     messages:
>     - '{completion:.2f}% utskrivet'
>     - 'Tid kvar: {printTimeLeft}'
>     - 'Klar: {ETA}'

The third message shows up for like 2-3 sec. Every message shows up correct.
Also, I have this in my log:

```
2017-12-13 17:04:34,435 - octoprint.plugins.detailedprogress - INFO - Caught an exception Unknown format code 'f' for object of type 'str'
Traceback:Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_detailedprogress/__init__.py", line 47, in do_work
    message = self._get_next_message(currentData)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_detailedprogress/__init__.py", line 81, in _get_next_message
    filepos = currentData["progress"]["filepos"]
ValueError: Unknown format code 'f' for object of type 'str'
```
What's wrong?¨

Edit: Seems to work just fine on my other printer. Same settings. Strange...

**Comment by nesalkiN** [comment]
Just reinstalled the plugin and now it works.. strange. :)
