### ISSUE TITLE
Your plugin rises exceptions !

### ISSUE THREAD

**Issue by azalanono** [dattas/OctoPrint-DetailedProgress#21]
Hi, Dattas Moonchaser.
Since some weeks (and several automated updates happening during this time) I noticed that the PSU Control plugin is not working as before. (-> other plugin, I know.)

Hereby I had a look into the logfile and see massive occurrences of following messages, I want to inform you about that so you can have a look on it and fix it.
```
2017-12-18 07:31:59,362 - octoprint.plugins.detailedprogress - INFO - Caught an exception Unknown format code 'f' for object of type 'str'
Traceback:Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_detailedprogress/__init__.py", line 47, in do_work
    message = self._get_next_message(currentData)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_detailedprogress/__init__.py", line 81, in _get_next_message
    filepos = currentData["progress"]["filepos"]
ValueError: Unknown format code 'f' for object of type 'str'
```
I am currently running octoprint 1.3.6

**Comment by sebaminguez** [comment]
Hi!
I think you should add the settings listed at the end of readme.md to your .octoprint/config.yaml file.

Best Regards
